name: Auto-generate PR Description

permissions:
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Generate PR Description
        uses: yuri-val/auto-pr-description-g4f-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          temperature: 0.7
          provider: auto
          model: gpt-4