name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publish-package:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.repository }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node 21
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Dependencies
        run: yarn

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}