name: Run Tests
on: push
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    env:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node 21
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install Dependencies
        run: yarn install

      - name: Run Jest Tests
        run: npm run test